version: '3.3'
services:
  web:
    build: ./docker/web
    container_name: suppharmacy
    depends_on:
      - api-db
    ports:
      - "8000:8000"
    volumes:
      - "./suppharmacy:/app"

    # For testing only
    stdin_open: true
    tty: true 
  
  api-db:
    build: ./docker/api
    container_name: api-db  
    depends_on:
      - db-master
    ports:
      - "8001:8000"
    volumes:
      - "./api-db:/app"

    # For testing only
    stdin_open: true
    tty: true

  db-master:
    image: postgres:14-bullseye
    container_name: db-master
    environment:
      POSTGRES_USER: suppharmacy
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: suppharmacy
    volumes:
      - "./pg-data:/var/lib/postgresql/data"
      - "./db-entrypoint:/docker-entrypoint-initdb.d/"
