# Generated by Django 4.1.3 on 2023-01-13 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sale", "0001_initial"),
        ("base", "0001_initial"),
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrugCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="ProductProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField()),
                ("code", models.CharField(max_length=15)),
                ("dealer_price", models.FloatField()),
                ("description", models.CharField(max_length=150)),
                ("expiration_time", models.DateField()),
                ("list_price", models.FloatField()),
                ("name", models.CharField(max_length=100)),
                ("qty_available", models.IntegerField()),
                ("sale_ok", models.BooleanField()),
                ("taxes", models.FloatField()),
                ("presentation", models.CharField(max_length=100)),
                ("is_antibiotic", models.BooleanField()),
                (
                    "drug_category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.drugcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResLaboratory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="StockQuant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("available_quantity", models.FloatField()),
                ("in_date", models.DateField()),
                ("quantity", models.FloatField()),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.productproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockPicking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("done", "Done"),
                            ("cancel", "Cancel"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "partner_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.respartner",
                    ),
                ),
                (
                    "sale_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sale.saleorder"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=100)),
                ("origin", models.CharField(max_length=100)),
                ("quantity_done", models.IntegerField()),
                ("product_qty", models.IntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("done", "Done"),
                            ("cancel", "Cancel"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "picking_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.stockpicking",
                    ),
                ),
                (
                    "purchase_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="purchase.purchaseorder",
                    ),
                ),
                (
                    "sale_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sale.saleorder"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="productproduct",
            name="laboratory_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stock.reslaboratory"
            ),
        ),
    ]
