# Generated by Django 4.1.3 on 2023-01-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockpicking",
            name="type_picking",
            field=models.CharField(
                choices=[
                    ("incoming", "Incoming"),
                    ("outgoing", "Outgoing"),
                    ("internal", "Internal"),
                ],
                default="incoming",
                max_length=50,
            ),
        ),
    ]
