# Generated by Django 4.1.3 on 2023-01-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_stockpicking_type_picking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drugcategory",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="reslaboratory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="stockmove",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="stockpicking",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
