# Generated by Django 4.1.3 on 2023-01-13 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField()),
                ("name", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("is_company", models.BooleanField()),
                ("mobile", models.CharField(max_length=15)),
                ("phone", models.CharField(max_length=15)),
                ("ref", models.CharField(max_length=100)),
                ("rfc", models.CharField(max_length=15)),
                ("cp", models.CharField(max_length=5)),
                (
                    "parent_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.respartner",
                    ),
                ),
            ],
        ),
    ]
