# Generated by Django 4.1.3 on 2023-01-13 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("purchase", "0001_initial"),
        ("base", "0001_initial"),
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderline",
            name="product_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stock.productproduct"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="partner_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.respartner"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
