# Generated by Django 4.1.3 on 2023-01-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
